const Padsd = [
  {
    "xy1457fff": {
      recovery: [
        {
          date_time: "2023-01-12T07:31:00",
          category: 'visita xxxsss',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-03-26T18:31:00",
          category: 'visita xyx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-01-15T09:31:00",
          category: 'ricovero xyy',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-07-26T18:31:00",
          category: 'ricovero xrx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
      ],
      visit: [
        {
          date_time: "2023-06-26T18:52:00",
          category: 'visita xxx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-03-26T18:31:00",
          category: 'visita xyx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-01-21T18:34:00",
          category: 'visita xyy',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-09-26T18:31:00",
          category: 'visita xrx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
      ],
      payment: [
        {
          date_time: "2023-05-26T18:31:00",
          category: 'fattura ',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-01-22T18:32:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-06-23T18:32:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-06-21T07:32:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-06-22T18:30:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2027-08-26T18:45:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
      ],
    },
    "xy1457uuu": {
      recovery: [
        // {
        //   date_time: "2023-02-26T18:31:00",
        //   category: 'visita xxx',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
        // {
        //   date_time: "2023-03-26T18:31:00",
        //   category: 'visita xyx',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
        {
          date_time: "2023-03-25T18:34:00",
          category: 'ricovero xyy',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        // {
        //   date_time: "2023-07-26T18:31:00",
        //   category: 'ricovero xrx',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
      ],
      visit: [
        {
          date_time: "2023-06-27T18:52:00",
          category: 'visita xxx',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        // {
        //   date_time: "2023-03-26T18:31:00",
        //   category: 'visita xyx',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
        {
          date_time: "2023-01-25T18:34:00",
          category: 'visita xyy',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        // {
        //   date_time: "2023-09-26T18:31:00",
        //   category: 'visita xrx',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
      ],
      payment: [
        // {
        //   date_time: "2023-05-26T18:31:00",
        //   category: 'fattura ',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
        // {
        //   date_time: "2023-01-25T18:32:00",
        //   category: 'fattura',
        //   amount: 50.70,
        //   note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
        //   paid: 0,
        // },
        {
          date_time: "2023-06-23T18:32:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-06-22T18:52:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2023-06-25T18:32:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
        {
          date_time: "2027-08-26T18:45:00",
          category: 'fattura',
          amount: 50.70,
          note: 'not malaria,not malaria,not malaria,not malaria,not malaria,',
          paid: 0,
        },
      ],
    }
    ,
  },
];

export default Padsd;