FROM node:19-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx:1.23.2-alpine

RUN apk add --no-cache bash gettext

COPY --from=build /app/build /usr/share/nginx/html

COPY docker/nginx.conf.template /etc/nginx/nginx.conf.template
COPY docker/react-static.conf.template /etc/nginx/templates/react-static.conf.template
COPY docker/nginx-conf-template.sh /docker-entrypoint.d/90-nginx-conf-template.sh

ENV WORKER_CONNECTIONS 1024
ENV WORKER_PROCESSES 2
ENV WORKER_NAME nginx
ENV MONITOR_PORT 8001

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]